# Generated by Django 3.0.2 on 2020-04-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, height_field=500, upload_to='products/%Y/%m/%d', width_field=500),
        ),
    ]
